# lesson-engine — local dev workflow
#
#   make            build dist/ and (re)start the server, tearing down any old one
#   make url        one-time: map http://learn.test → the server via Caddy (uses sudo)
#   make stop       stop the dev server
#   make status     show server + proxy state
#   make logs       tail the server log
#   make help       list all targets
#
# The server (`npm start`) serves the built dist/, so a run always rebuilds first.
# `build` calls vite directly, skipping the typecheck for speed; content is not
# part of the build at all — it is served live from the data dir.

SHELL      := /bin/bash
PORT       ?= 4173
HOST       := learn.test
BREWPREFIX := $(shell brew --prefix 2>/dev/null)
CADDYFILE  := $(BREWPREFIX)/etc/Caddyfile
LOG        := .dev-server.log
PIDFILE    := .dev-server.pid

.DEFAULT_GOAL := dev
.PHONY: dev restart build validate stop status logs url help

dev: build stop ## Build, tear down any running server, then start fresh (default)
	@echo "· starting npm start on :$(PORT)…"; \
	nohup npm start > $(LOG) 2>&1 < /dev/null & echo $$! > $(PIDFILE); \
	for i in $$(seq 1 40); do \
		if curl -sf -o /dev/null http://localhost:$(PORT)/; then \
			echo "✔ server up  — http://localhost:$(PORT)  (pid $$(cat $(PIDFILE)))"; \
			if grep -q "$(HOST)" /etc/hosts 2>/dev/null && curl -sf -o /dev/null http://$(HOST)/ 2>/dev/null; then \
				echo "✔ proxy up   — http://$(HOST)"; \
			else \
				echo "ℹ  http://$(HOST) not wired — run 'make url' once (uses sudo)"; \
			fi; \
			exit 0; \
		fi; sleep 0.25; \
	done; \
	echo "✗ server failed to start — last log lines:"; tail -n 20 $(LOG); exit 1

restart: dev ## Alias for the default build-and-restart flow

build: ## Rebuild dist/ (vite only; `npm run build` adds the typecheck)
	npx vite build

validate: ## Validate the data-dir content (advisory authoring aid)
	-npm run validate

stop: ## Stop any dev server on the dev port (4173)
	@pids=$$(lsof -ti tcp:$(PORT) 2>/dev/null || true); \
	if [ -n "$$pids" ]; then \
		echo "· stopping server on :$(PORT) ($$pids)"; \
		kill $$pids 2>/dev/null || true; sleep 1; \
		still=$$(lsof -ti tcp:$(PORT) 2>/dev/null || true); \
		[ -n "$$still" ] && kill -9 $$still 2>/dev/null || true; \
	else echo "· no server running on :$(PORT)"; fi; \
	rm -f $(PIDFILE)

status: ## Show server + proxy state
	@lsof -ti tcp:$(PORT) >/dev/null 2>&1 \
		&& echo "server : up on :$(PORT)" || echo "server : down"; \
	grep -q "$(HOST)" /etc/hosts 2>/dev/null \
		&& echo "hosts  : $(HOST) → 127.0.0.1" || echo "hosts  : $(HOST) not mapped (make url)"; \
	curl -sf -o /dev/null http://$(HOST)/ 2>/dev/null \
		&& echo "proxy  : up — http://$(HOST)" || echo "proxy  : down (make url)"

logs: ## Tail the dev server log
	@touch $(LOG); tail -f $(LOG)

url: ## One-time: install/point Caddy so http://learn.test works (uses sudo)
	@command -v caddy >/dev/null 2>&1 || { echo "· installing caddy…"; brew install caddy; }
	@if grep -q "$(HOST)" /etc/hosts 2>/dev/null; then \
		echo "· /etc/hosts already maps $(HOST)"; \
	else \
		echo "· adding $(HOST) to /etc/hosts (sudo)…"; \
		echo "127.0.0.1 $(HOST)" | sudo tee -a /etc/hosts >/dev/null; \
	fi
	@if [ -s "$(CADDYFILE)" ] && ! grep -q 'lesson-engine local dev' "$(CADDYFILE)"; then \
		echo "✗ $(CADDYFILE) has existing config that isn't ours — refusing to overwrite."; \
		echo "  Add the http://$(HOST) site block to it by hand, then restart caddy."; \
		exit 1; \
	fi
	@printf '%s\n' \
		'# lesson-engine local dev — http://$(HOST) → npm start (localhost:$(PORT))' \
		'# Regenerated by: make url' \
		'http://$(HOST) {' \
		'    reverse_proxy localhost:$(PORT)' \
		'}' > $(CADDYFILE)
	@echo "· (re)starting caddy (sudo)…"; sudo brew services restart caddy
	@sleep 1; curl -sf -o /dev/null http://$(HOST)/ 2>/dev/null \
		&& echo "✔ http://$(HOST) → localhost:$(PORT)" \
		|| echo "ℹ  caddy restarted; run 'make dev' if the server isn't up yet"

help: ## List all targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| sort | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-9s\033[0m %s\n", $$1, $$2}'
